spring:
  datasource:
    url: jdbc:postgresql://$AZ_DATABASE_NAME:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: $AZ_DATABASE_NAME
    password: $AZ_POSTGRESQL_PASSWORD
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update